name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
    
    - name: Render Quarto Project
      run: |
        cd presentations/test-presentation
        quarto render index.qmd -t revealjs
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./presentations
